<?php

namespace AppBundle\Repository;

/**
 * VerbRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VerbRepository extends \Doctrine\ORM\EntityRepository
{
}
