<?php

namespace AppBundle\Repository;

/**
 * VerbTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VerbTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
